services:

  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    user: "${UID}:${GID}"
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./var:/var
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'production' ];
             then bun run start;
             else bun run dev;
             fi"
    ports:
      - "${HTTP_PORT}:3000"